### ISSUE TITLE
blade vortex

### ISSUE THREAD

**Issue by ghost** [IncubusX/ScourgeArrowCharges#1]
подойдет данная рутина для bv?

**Comment by chuykin** [comment]
Да, подойдет для любых скиллов которые накладывают баф на персонажа.

**Comment by ghost** [comment]
@IncubusX https://gist.github.com/jaspergould/431641292d8876af27003101ec8c7792 сделал так, но не особо работоспособно.

**Comment by chuykin** [comment]
@jaspergould А какого именно поведения нужно добиться? В данный момент при зажатии указанной клавиши мыши идет проверка на количество стаков бафа, при достижении нужного числи вызывает отпускание клавиши и повторное зажатие. Если нужно изменить поведение при накоплении максимального количества стаков, то нужно менять MouseLeft(Right)ClickEvent().

**Comment by ghost** [comment]
@IncubusX делать паузы на сек 5. Но надо намутить что-то с временем окончания new_blade_vortex

**Comment by chuykin** [comment]
@jaspergould Для автокаста и пауз лучше использовать [BYOR](https://github.com/sychotixdev/BuildYourOwnRoutine).

**Comment by ghost** [comment]
@IncubusX время есть поколупать bv в студии?
